### ISSUE TITLE
 No module named 'fcntl'

### ISSUE THREAD

**Issue by rijusougata13** [ShaylanDias/Heroku-React-Flask#1]
npm start giving the error " No module named 'fcntl'"

**Comment by ShaylanDias** [comment]
Hi, I am fairly sure there is no 'fcntl' dependency for this project.

Did you make sure to run `npm install` and `npm run build` befpre attempting to start?

**Comment by rijusougata13** [comment]
flask-react\.venv\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl

when i install gunicorn  there is a line import fcntl ..i found in internet fcntl doesn;t support in win ..so do you know how to fix this?

**Comment by ShaylanDias** [comment]
Gunicorn is built for a UNIX environment so you won't be able to run it on Windows. You have a couple options.
1. Run it in a VM
2. Deploy it to Heroku (as this is project meant for), Heroku runs a UNIX-based environment so this will work when deployed.
3. Use a different webserver instead of gunicorn. If you do feel free to submit a pull request and I'll see how I can add your code to this repo in a way that makes sense.

**Comment by rijusougata13** [comment]
then how can i run this in locally.when i use npm start it will giving me this error

**Comment by ShaylanDias** [comment]
Follow one of the three options I gave you above: https://stackshare.io/gunicorn/alternatives
You can run Flask with its own webserver it's just not recommended for production.

**Comment by TuringNPcomplete** [comment]
If you are trying to run heroku locally on a windows machine, you should try the code below instead of the usual `heroku  local`

`heroku local web -f Procfile.windows`
